{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gsm-secs-{{ .Release.Name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.gsmServiceAccount }}
spec:
  provider: gke
  secretObjects:
  - secretName: {{ include "app.fullname" . }}-secrets
    type: Opaque
    data:
    {{- if .Values.database.enabled }}
    - objectName: {{ .Values.secretNames.databaseUrl | default "database_url" }}
      key: DATABASE_URL
    {{- end }}
    {{- range .Values.secretProvider.secrets }}
    - objectName: {{ .objectName }}
      key: {{ .key }}
    {{- end }}
  parameters:
    secrets: |-
      {{- if .Values.database.enabled }}
      - resourceName: projects/{{ .Values.gcpProject }}/secrets/{{ .Values.secretNames.databaseUrl | default "database_url" }}/versions/latest
        path: {{ .Values.secretNames.databaseUrl | default "database_url" }}
      {{- end }}
      {{- range .Values.secretProvider.secrets }}
      - resourceName: projects/{{ $.Values.gcpProject }}/secrets/{{ .secretName }}/versions/latest
        path: {{ .objectName }}
      {{- end }}
{{- end }}